# Generated by Django 5.0.6 on 2025-03-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('card', 'بطاقة ائتمان'), ('online', 'محفظة الكترونية')], max_length=20),
        ),
    ]
