# Generated by Django 5.0.6 on 2025-03-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_status_coupon_use_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(choices=[('مفعل', 'مفعل'), ('معطل', 'معطل')], default='مفعل', max_length=20),
        ),
    ]
