# Generated by Django 5.0.6 on 2025-03-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='number_of_seats',
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('متاحة', 'متاحة'), ('محجوزة', 'محجوزة')], default='متاحة', max_length=20),
        ),
    ]
