# Generated by Django 5.0.6 on 2025-03-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_number_table_number_of_seats_table_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
