# Generated by Django 5.0.6 on 2025-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='categories/'),
        ),
    ]
