# Generated by Django 5.0.6 on 2025-03-11 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0003_remove_table_name_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'حضور'), ('take_out', 'طلب للخارج'), ('delivery', 'توصيل')], default='dine_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('قيد التنفيذ', 'قيد التنفيذ'), ('في الطريق', 'في الطريق'), ('تم التسليم', 'تم التسليم'), ('تم التأكيد', 'تم التأكيد'), ('تم الغاء', 'تم الغاء')], default='قيد التنفيذ', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table'),
        ),
    ]
